---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.1.1

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[sample-cookbook::default]
    attributes:
